// Generated by gencpp from file mavros_msgs/SpeedControlSet.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_SPEEDCONTROLSET_H
#define MAVROS_MSGS_MESSAGE_SPEEDCONTROLSET_H

#include <ros/service_traits.h>


#include <mavros_msgs/SpeedControlSetRequest.h>
#include <mavros_msgs/SpeedControlSetResponse.h>


namespace mavros_msgs
{

struct SpeedControlSet
{

typedef SpeedControlSetRequest Request;
typedef SpeedControlSetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpeedControlSet
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::SpeedControlSet > {
  static const char* value()
  {
    return "6a0060d83b9d2b0d745139269e8066b7";
  }

  static const char* value(const ::mavros_msgs::SpeedControlSet&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::SpeedControlSet > {
  static const char* value()
  {
    return "mavros_msgs/SpeedControlSet";
  }

  static const char* value(const ::mavros_msgs::SpeedControlSet&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::SpeedControlSetRequest> should match
// service_traits::MD5Sum< ::mavros_msgs::SpeedControlSet >
template<>
struct MD5Sum< ::mavros_msgs::SpeedControlSetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::SpeedControlSet >::value();
  }
  static const char* value(const ::mavros_msgs::SpeedControlSetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::SpeedControlSetRequest> should match
// service_traits::DataType< ::mavros_msgs::SpeedControlSet >
template<>
struct DataType< ::mavros_msgs::SpeedControlSetRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::SpeedControlSet >::value();
  }
  static const char* value(const ::mavros_msgs::SpeedControlSetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::SpeedControlSetResponse> should match
// service_traits::MD5Sum< ::mavros_msgs::SpeedControlSet >
template<>
struct MD5Sum< ::mavros_msgs::SpeedControlSetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::SpeedControlSet >::value();
  }
  static const char* value(const ::mavros_msgs::SpeedControlSetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::SpeedControlSetResponse> should match
// service_traits::DataType< ::mavros_msgs::SpeedControlSet >
template<>
struct DataType< ::mavros_msgs::SpeedControlSetResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::SpeedControlSet >::value();
  }
  static const char* value(const ::mavros_msgs::SpeedControlSetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_SPEEDCONTROLSET_H
