# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mavros_msgs/Posture.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Posture(genpy.Message):
  _md5sum = "9c16718438cf31bb244fa8df603829bf"
  _type = "mavros_msgs/Posture"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 pos_x_state
float32 pos_y_state
float32 zangle_state
float32 xangle_state
float32 yangle_state
float32 w_z_state

std_msgs/Header header
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['pos_x_state','pos_y_state','zangle_state','xangle_state','yangle_state','w_z_state','header']
  _slot_types = ['float32','float32','float32','float32','float32','float32','std_msgs/Header']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pos_x_state,pos_y_state,zangle_state,xangle_state,yangle_state,w_z_state,header

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Posture, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pos_x_state is None:
        self.pos_x_state = 0.
      if self.pos_y_state is None:
        self.pos_y_state = 0.
      if self.zangle_state is None:
        self.zangle_state = 0.
      if self.xangle_state is None:
        self.xangle_state = 0.
      if self.yangle_state is None:
        self.yangle_state = 0.
      if self.w_z_state is None:
        self.w_z_state = 0.
      if self.header is None:
        self.header = std_msgs.msg.Header()
    else:
      self.pos_x_state = 0.
      self.pos_y_state = 0.
      self.zangle_state = 0.
      self.xangle_state = 0.
      self.yangle_state = 0.
      self.w_z_state = 0.
      self.header = std_msgs.msg.Header()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f3I().pack(_x.pos_x_state, _x.pos_y_state, _x.zangle_state, _x.xangle_state, _x.yangle_state, _x.w_z_state, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.pos_x_state, _x.pos_y_state, _x.zangle_state, _x.xangle_state, _x.yangle_state, _x.w_z_state, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_6f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f3I().pack(_x.pos_x_state, _x.pos_y_state, _x.zangle_state, _x.xangle_state, _x.yangle_state, _x.w_z_state, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.pos_x_state, _x.pos_y_state, _x.zangle_state, _x.xangle_state, _x.yangle_state, _x.w_z_state, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_6f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f3I = None
def _get_struct_6f3I():
    global _struct_6f3I
    if _struct_6f3I is None:
        _struct_6f3I = struct.Struct("<6f3I")
    return _struct_6f3I
